diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=blt-darklight
user.email=840335129@qq.com
user.useconfigonly=true
credential.https://gitee.com.provider=generic
core.quotepath=false
core.longpaths=true
core.autocrlf=true
core.trustctime=false
core.excludesfile=~/.gitignore_global
core.attributesfile=~/.attributes_global
core.ignorecase=true
core.untrackedcache=true
init.defaultbranch=master
http.postbuffer=655360000
http.sslcainfo=C:\Users\walnut\AppData\Local\UGit\ssl\certs\ca-bundle.trust.crt
http.sslbackend=schannel
diff.text.textconv=cat
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
mergetool.keepbackup=false
lfs.concurrenttransfers=32
lfs.fetchrecentrefsdays=0
lfs.pruneoffsetdays=0
lfs.dialtimeout=3
lfs.tlstimeout=3
merge.lfs-text.driver=git lfs merge-driver --ancestor %O --current %A --other %B --marker-size %L --output %A --program 'git merge-file --stdout --marker-size=%%L %%A %%O %%B >%%D'
rebase.backend=merge
protocol.version=1
pull.rebase=false
safe.directory=*
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
